import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo app',
  description: 'Generated by create next app',
}

const urls = {
  Home: '/',
  Demo: '/demo',
  About: '/about',
  Person: '/person',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar urls={urls} />
        {children}
      </body>
    </html>
  )
}
